-- Data Subject Access Requests (GDPR DSAR queue)
-- ---------------------------------------------------------------------------
-- A customer taps "Request my data" → a row lands here as 'pending'. An admin /
-- DPO then verifies identity, generates + redacts the export, and releases it
-- (emailing the customer). Nothing is auto-released — every request is reviewed.
--
-- Safe to run multiple times.

create table if not exists public.data_requests (
  id           bigint generated by default as identity primary key,
  user_id      uuid not null references public.profiles(id) on delete cascade,
  user_email   text,
  user_name    text,
  type         text not null default 'export',     -- 'export' (extendable: 'erasure', …)
  status       text not null default 'pending',     -- pending | verifying | ready | released | rejected
  notes        text,                                -- DPO notes / rejection reason
  handled_by   uuid,                                -- admin who actioned it
  requested_at timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);
create index if not exists data_requests_status_idx on public.data_requests(status);
create index if not exists data_requests_user_idx   on public.data_requests(user_id);

alter table public.data_requests enable row level security;

-- A signed-in user may create their OWN request…
drop policy if exists data_requests_insert_own on public.data_requests;
create policy data_requests_insert_own on public.data_requests
  for insert to authenticated
  with check (user_id = auth.uid());

-- …and read their own; admins read everything.
drop policy if exists data_requests_select on public.data_requests;
create policy data_requests_select on public.data_requests
  for select to authenticated
  using (
    user_id = auth.uid()
    or coalesce((auth.jwt() -> 'app_metadata' ->> 'role'), '') in ('admin','super_admin')
  );

-- Only admins move a request through the workflow.
drop policy if exists data_requests_admin_update on public.data_requests;
create policy data_requests_admin_update on public.data_requests
  for update to authenticated
  using      (coalesce((auth.jwt() -> 'app_metadata' ->> 'role'), '') in ('admin','super_admin'))
  with check (coalesce((auth.jwt() -> 'app_metadata' ->> 'role'), '') in ('admin','super_admin'));

grant select, insert, update on public.data_requests to authenticated;
