-- Data Subject Access Requests (GDPR DSAR queue) + email-OTP verification
-- ---------------------------------------------------------------------------
-- A customer taps "Request my data" → must verify a 6-digit code emailed to their
-- account address → only then is a 'pending' row created (server-side, after the
-- code checks out). An admin / DPO then verifies, generates + redacts the export,
-- and releases it (emailing the customer). Nothing is auto-released.
--
-- Safe to run multiple times.

create table if not exists public.data_requests (
  id           bigint generated by default as identity primary key,
  user_id      uuid not null references public.profiles(id) on delete cascade,
  user_email   text,
  user_name    text,
  type         text not null default 'export',     -- 'export' (extendable)
  status       text not null default 'pending',     -- pending | verifying | ready | released | rejected
  notes        text,
  handled_by   uuid,
  requested_at timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);
create index if not exists data_requests_status_idx on public.data_requests(status);
create index if not exists data_requests_user_idx   on public.data_requests(user_id);

alter table public.data_requests enable row level security;

-- Requests are created ONLY by the server (service role, after OTP) — no client insert.
drop policy if exists data_requests_insert_own on public.data_requests;
revoke insert on public.data_requests from authenticated;

-- Users read their own; admins read everything.
drop policy if exists data_requests_select on public.data_requests;
create policy data_requests_select on public.data_requests
  for select to authenticated
  using (
    user_id = auth.uid()
    or coalesce((auth.jwt() -> 'app_metadata' ->> 'role'), '') in ('admin','super_admin')
  );

-- Only admins move a request through the workflow.
drop policy if exists data_requests_admin_update on public.data_requests;
create policy data_requests_admin_update on public.data_requests
  for update to authenticated
  using      (coalesce((auth.jwt() -> 'app_metadata' ->> 'role'), '') in ('admin','super_admin'))
  with check (coalesce((auth.jwt() -> 'app_metadata' ->> 'role'), '') in ('admin','super_admin'));

grant select, update on public.data_requests to authenticated;

-- One-time email-OTP store for verifying a data request. Touched ONLY by the
-- server (service role) — RLS is on with no policies, so no client can read/write it.
create table if not exists public.data_request_otp (
  user_id    uuid primary key references public.profiles(id) on delete cascade,
  code_hash  text not null,
  expires_at timestamptz not null,
  attempts   int  not null default 0,
  created_at timestamptz not null default now()
);
alter table public.data_request_otp enable row level security;
revoke all on public.data_request_otp from anon, authenticated;
