-- ════════════════════════════════════════════════════════════════════
-- event_rsvps — RSVPs for community events, with organiser-only attendance
-- check-in. Powers the "Attendees" panel that shows ONLY to the event's
-- organiser (community_events.user_id), with a per-attendee Check-in toggle.
--
-- Run this once in the Supabase SQL Editor. Safe to run twice (idempotent).
-- Assumes public.profiles.id is uuid and equals auth.uid(), and that
-- public.community_events.user_id is the organiser. Confirm in the dashboard
-- before running.
-- ════════════════════════════════════════════════════════════════════

create table if not exists public.event_rsvps (
  id            bigint generated by default as identity primary key,
  event_id      bigint references public.community_events(id) on delete cascade,
  user_id       uuid   references public.profiles(id)        on delete cascade,
  checked_in    boolean     not null default false,
  checked_in_at timestamptz,
  created_at    timestamptz not null default now(),
  unique (event_id, user_id)
);

-- Defensive: add the attendance columns if an older table already exists.
alter table public.event_rsvps add column if not exists checked_in    boolean     not null default false;
alter table public.event_rsvps add column if not exists checked_in_at timestamptz;
alter table public.event_rsvps add column if not exists created_at    timestamptz not null default now();

create index if not exists event_rsvps_event_idx on public.event_rsvps (event_id);
create index if not exists event_rsvps_user_idx  on public.event_rsvps (user_id);

alter table public.event_rsvps enable row level security;

-- ── RLS ──────────────────────────────────────────────────────────────
-- A signed-in user may RSVP themselves (own row only).
drop policy if exists "rsvp insert own" on public.event_rsvps;
create policy "rsvp insert own"
  on public.event_rsvps for insert to authenticated
  with check (auth.uid() = user_id);

-- A user may cancel their own RSVP.
drop policy if exists "rsvp delete own" on public.event_rsvps;
create policy "rsvp delete own"
  on public.event_rsvps for delete to authenticated
  using (auth.uid() = user_id);

-- SELECT: a user can see their own RSVP, AND the event's organiser can see
-- every RSVP for that event (this is what makes the attendee list work, and
-- keeps it private to the organiser — no one else can read others' RSVPs).
drop policy if exists "rsvp select own or organiser" on public.event_rsvps;
create policy "rsvp select own or organiser"
  on public.event_rsvps for select to authenticated
  using (
    auth.uid() = user_id
    or exists (
      select 1 from public.community_events e
      where e.id = event_rsvps.event_id and e.user_id = auth.uid()
    )
  );

-- UPDATE (check-in / undo): only the event's organiser may flip checked_in.
drop policy if exists "rsvp update organiser" on public.event_rsvps;
create policy "rsvp update organiser"
  on public.event_rsvps for update to authenticated
  using (
    exists (
      select 1 from public.community_events e
      where e.id = event_rsvps.event_id and e.user_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1 from public.community_events e
      where e.id = event_rsvps.event_id and e.user_id = auth.uid()
    )
  );

-- ── profiles read for organisers ─────────────────────────────────────
-- The attendee list joins profiles(name,email). For those names to show, the
-- organiser must be able to read the profile rows of people who RSVP'd to
-- their events. This policy is scoped to exactly that relationship.
drop policy if exists "organiser reads attendee profiles" on public.profiles;
create policy "organiser reads attendee profiles"
  on public.profiles for select to authenticated
  using (
    exists (
      select 1
      from public.event_rsvps r
      join public.community_events e on e.id = r.event_id
      where r.user_id = profiles.id and e.user_id = auth.uid()
    )
  );
