-- No-show reporting
-- ---------------------------------------------------------------------------
-- Merchants flag customers who reserved an arrival time but never showed up.
-- Each report bumps a per-customer counter (visible to the customer and to
-- admins) and writes an audit row. Admins review the counter to decide whether
-- to inactivate the account or deduct Appie Credits — nothing is automatic.
--
-- Safe to run multiple times (IF NOT EXISTS / OR REPLACE guards).

-- 1. Per-customer running counter.
alter table public.profiles
  add column if not exists no_show_count int not null default 0;

-- 2. Audit log: one row per reported booking. The unique index on booking_id
--    means a merchant can't inflate the count by reporting the same booking
--    twice.
create table if not exists public.no_shows (
  id                  bigint generated by default as identity primary key,
  user_id             uuid not null references public.profiles(id) on delete cascade,
  booking_id          bigint,
  purchase_id         bigint,
  deal_id             bigint,
  venue_id            uuid,
  venue_name          text,
  deal_title          text,
  reported_by         uuid,            -- merchant (auth uid) who reported it
  created_at          timestamptz not null default now()
);
create unique index if not exists no_shows_booking_uq
  on public.no_shows(booking_id) where booking_id is not null;
create index if not exists no_shows_user_idx on public.no_shows(user_id);

alter table public.no_shows enable row level security;

-- Customers see their own no-shows; admins see all. Inserts go through the
-- SECURITY DEFINER function below, so clients never insert directly.
drop policy if exists no_shows_select_own on public.no_shows;
create policy no_shows_select_own on public.no_shows
  for select using (
    auth.uid() = user_id
    or coalesce((auth.jwt() -> 'app_metadata' ->> 'role'), '') in ('admin','super_admin')
  );

-- 3. Allow the booking status to record a no-show (the original CHECK only
--    permitted 'confirmed'/'cancelled').
alter table public.voucher_bookings
  drop constraint if exists voucher_bookings_status_check;
alter table public.voucher_bookings
  add constraint voucher_bookings_status_check
  check (status in ('confirmed','cancelled','no_show'));

-- 4. Report a no-show. SECURITY DEFINER so a merchant may increment ANOTHER
--    user's profile counter — but only after we verify the merchant owns the
--    venue/deal behind the booking. Idempotent: a second call for the same
--    booking is a no-op. Returns the customer's new counter.
create or replace function public.report_no_show(p_booking_id bigint)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_caller      uuid := auth.uid();
  v_role        text := coalesce((auth.jwt() -> 'app_metadata' ->> 'role'), '');
  v_user_id     uuid;
  v_deal_id     bigint;
  v_purchase_id bigint;
  v_venue_id    uuid;
  v_owner_id    uuid;
  v_venue_name  text;
  v_deal_title  text;
  v_already     boolean;
  v_new_count   int;
begin
  if v_caller is null then
    raise exception 'Not authenticated';
  end if;

  -- Load the booking + its deal/venue/customer.
  select b.user_id, b.deal_id, b.purchase_id,
         d.title, d.venue_id, v.owner_id, v.name
    into v_user_id, v_deal_id, v_purchase_id,
         v_deal_title, v_venue_id, v_owner_id, v_venue_name
  from public.voucher_bookings b
  left join public.deals  d on d.id = b.deal_id
  left join public.venues v on v.id = d.venue_id
  where b.id = p_booking_id;

  if v_user_id is null then
    raise exception 'Booking not found';
  end if;

  -- Authorization: caller must own the venue behind this booking (admins bypass).
  if v_role not in ('admin','super_admin')
     and (v_owner_id is null or v_owner_id <> v_caller) then
    raise exception 'Not authorized to report this booking';
  end if;

  -- A redeemed voucher means the customer DID show up — refuse.
  if v_purchase_id is not null then
    perform 1 from public.voucher_purchases
      where id = v_purchase_id and status = 'used';
    if found then
      raise exception 'Voucher already redeemed — cannot mark as no-show';
    end if;
  end if;

  -- Idempotency: has this booking already been flagged?
  select exists(select 1 from public.no_shows where booking_id = p_booking_id)
    into v_already;

  if not v_already then
    insert into public.no_shows(
      user_id, booking_id, purchase_id, deal_id, venue_id, venue_name, deal_title, reported_by)
    values (
      v_user_id, p_booking_id, v_purchase_id, v_deal_id, v_venue_id, v_venue_name, v_deal_title, v_caller);

    update public.profiles
       set no_show_count = coalesce(no_show_count,0) + 1
     where id = v_user_id;

    update public.voucher_bookings set status = 'no_show' where id = p_booking_id;
  end if;

  select coalesce(no_show_count,0) into v_new_count
    from public.profiles where id = v_user_id;
  return v_new_count;
end;
$$;

grant execute on function public.report_no_show(bigint) to authenticated;

-- 5. Undo a mistaken no-show (same ownership check). Returns the new counter.
create or replace function public.undo_no_show(p_booking_id bigint)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_caller   uuid := auth.uid();
  v_role     text := coalesce((auth.jwt() -> 'app_metadata' ->> 'role'), '');
  v_user_id  uuid;
  v_owner_id uuid;
  v_new      int;
begin
  if v_caller is null then raise exception 'Not authenticated'; end if;

  select ns.user_id into v_user_id
    from public.no_shows ns where ns.booking_id = p_booking_id;

  -- Nothing logged → just report the current counter for that booking's user.
  if v_user_id is null then
    select coalesce(p.no_show_count,0) into v_new
      from public.voucher_bookings b
      join public.profiles p on p.id = b.user_id
     where b.id = p_booking_id;
    return coalesce(v_new,0);
  end if;

  select v.owner_id into v_owner_id
    from public.voucher_bookings b
    join public.deals  d on d.id = b.deal_id
    join public.venues v on v.id = d.venue_id
   where b.id = p_booking_id;

  if v_role not in ('admin','super_admin')
     and (v_owner_id is null or v_owner_id <> v_caller) then
    raise exception 'Not authorized';
  end if;

  delete from public.no_shows where booking_id = p_booking_id;
  update public.profiles
     set no_show_count = greatest(0, coalesce(no_show_count,0) - 1)
   where id = v_user_id;
  update public.voucher_bookings set status = 'confirmed' where id = p_booking_id;

  select coalesce(no_show_count,0) into v_new from public.profiles where id = v_user_id;
  return v_new;
end;
$$;

grant execute on function public.undo_no_show(bigint) to authenticated;
