-- Web Push subscriptions (OS-level notifications for Home-Screen PWAs, iOS 16.4+/Android/desktop)
-- ---------------------------------------------------------------------------
-- The browser subscribes via the Push API and stores its subscription here
-- (one row per device/endpoint). The server (api/send-push.js, service role)
-- reads these to fan out notifications via VAPID/web-push. Owners manage only
-- their own rows; the send endpoint uses the service-role key and bypasses RLS.
--
-- Safe to run multiple times.

create table if not exists public.push_subscriptions (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null references public.profiles(id) on delete cascade,
  endpoint    text not null unique,           -- the push service URL (unique per device)
  p256dh      text not null,                  -- client public key
  auth        text not null,                  -- client auth secret
  user_agent  text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create index if not exists push_subscriptions_user_idx on public.push_subscriptions(user_id);

alter table public.push_subscriptions enable row level security;

-- Owners read their own subscriptions.
drop policy if exists "push_subs owner select" on public.push_subscriptions;
create policy "push_subs owner select" on public.push_subscriptions
  for select to authenticated using (auth.uid() = user_id);

-- Owners register their own subscription (user_id must be themselves).
drop policy if exists "push_subs owner insert" on public.push_subscriptions;
create policy "push_subs owner insert" on public.push_subscriptions
  for insert to authenticated with check (auth.uid() = user_id);

-- Owners update their own (used by the upsert-on-endpoint refresh).
drop policy if exists "push_subs owner update" on public.push_subscriptions;
create policy "push_subs owner update" on public.push_subscriptions
  for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Owners remove their own (disable notifications / clean up).
drop policy if exists "push_subs owner delete" on public.push_subscriptions;
create policy "push_subs owner delete" on public.push_subscriptions
  for delete to authenticated using (auth.uid() = user_id);

grant select, insert, update, delete on public.push_subscriptions to authenticated;
