-- ════════════════════════════════════════════════════════════════════
-- HappyHourly — one-shot setup for the recently added features.
-- Paste this WHOLE file into the Supabase SQL Editor and click "Run".
-- Safe to run more than once (everything is idempotent).
--
-- Covers:
--   1) Profile photos          → profiles.avatar_url
--   2) HappyCash wallet         → profiles.wallet_balance + wallet_ledger
--   3) Event attendance/check-in→ event_rsvps columns + RLS
--   4) "Where to Watch" reports → screening_reports
-- ════════════════════════════════════════════════════════════════════


-- ── 1) Profile photo + 2) wallet balance (columns on profiles) ───────
alter table public.profiles add column if not exists avatar_url     text;
alter table public.profiles add column if not exists wallet_balance numeric(12,2) not null default 0;


-- ── 2) Wallet ledger (optional history of conversions/spends) ────────
create table if not exists public.wallet_ledger (
  id          bigint generated by default as identity primary key,
  user_id     uuid references public.profiles(id) on delete cascade,
  kind        text not null,             -- 'convert_in' | 'spend' | 'admin_adjust'
  credits     integer,
  euros       numeric(12,2) not null,
  ref         text,
  created_at  timestamptz not null default now()
);
create index if not exists wallet_ledger_user_idx on public.wallet_ledger (user_id, created_at desc);
alter table public.wallet_ledger enable row level security;
drop policy if exists "wallet_ledger own read"   on public.wallet_ledger;
create policy "wallet_ledger own read"   on public.wallet_ledger for select to authenticated using (auth.uid() = user_id);
drop policy if exists "wallet_ledger own insert" on public.wallet_ledger;
create policy "wallet_ledger own insert" on public.wallet_ledger for insert to authenticated with check (auth.uid() = user_id);


-- ── 3) Event attendance: RSVPs + organiser-only check-in ─────────────
create table if not exists public.event_rsvps (
  id            bigint generated by default as identity primary key,
  event_id      bigint references public.community_events(id) on delete cascade,
  user_id       uuid   references public.profiles(id)         on delete cascade,
  checked_in    boolean     not null default false,
  checked_in_at timestamptz,
  created_at    timestamptz not null default now(),
  unique (event_id, user_id)
);
alter table public.event_rsvps add column if not exists checked_in    boolean     not null default false;
alter table public.event_rsvps add column if not exists checked_in_at timestamptz;
alter table public.event_rsvps add column if not exists created_at    timestamptz not null default now();
create index if not exists event_rsvps_event_idx on public.event_rsvps (event_id);
create index if not exists event_rsvps_user_idx  on public.event_rsvps (user_id);
alter table public.event_rsvps enable row level security;

drop policy if exists "rsvp insert own" on public.event_rsvps;
create policy "rsvp insert own" on public.event_rsvps for insert to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "rsvp delete own" on public.event_rsvps;
create policy "rsvp delete own" on public.event_rsvps for delete to authenticated
  using (auth.uid() = user_id);

drop policy if exists "rsvp select own or organiser" on public.event_rsvps;
create policy "rsvp select own or organiser" on public.event_rsvps for select to authenticated
  using (
    auth.uid() = user_id
    or exists (select 1 from public.community_events e where e.id = event_rsvps.event_id and e.user_id = auth.uid())
  );

drop policy if exists "rsvp update organiser" on public.event_rsvps;
create policy "rsvp update organiser" on public.event_rsvps for update to authenticated
  using     (exists (select 1 from public.community_events e where e.id = event_rsvps.event_id and e.user_id = auth.uid()))
  with check(exists (select 1 from public.community_events e where e.id = event_rsvps.event_id and e.user_id = auth.uid()));

-- Let an organiser read the profiles (name/email) of people who RSVP'd to their events.
drop policy if exists "organiser reads attendee profiles" on public.profiles;
create policy "organiser reads attendee profiles" on public.profiles for select to authenticated
  using (
    exists (
      select 1 from public.event_rsvps r
      join public.community_events e on e.id = r.event_id
      where r.user_id = profiles.id and e.user_id = auth.uid()
    )
  );


-- ── 4) "Where to Watch" report-info (screening_reports) ──────────────
-- Requires the match_screenings table (run match_screenings.sql if you haven't).
create table if not exists public.screening_reports (
  id                   bigint generated by default as identity primary key,
  screening_id         bigint references public.match_screenings(id) on delete cascade,
  user_id              uuid,
  reporter_name        text,
  reporter_email       text,
  field_reported       text,
  suggested_correction text,
  additional_comments  text,
  status               text default 'pending',
  created_at           timestamptz not null default now()
);
create index if not exists screening_reports_status_idx on public.screening_reports (status, created_at);
alter table public.screening_reports enable row level security;
drop policy if exists "screening_reports insert" on public.screening_reports;
create policy "screening_reports insert" on public.screening_reports for insert to authenticated with check (true);
drop policy if exists "screening_reports read" on public.screening_reports;
create policy "screening_reports read" on public.screening_reports for select using (true);
drop policy if exists "screening_reports update" on public.screening_reports;
create policy "screening_reports update" on public.screening_reports for update to authenticated
  using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('admin','super_admin')))
  with check (true);
