-- ════════════════════════════════════════════════════════════════════
-- HappyCash wallet — store-credit balance customers top up by converting
-- their HappyCredits, then spend at checkout.
--
-- The conversion rate (credits per €1) is configured by admins in the app's
-- Credits config (app_config key 'creditsConfig' → conversion), not here.
--
-- Run once in the Supabase SQL Editor. Safe to run twice (idempotent).
-- Assumes public.profiles holds the per-user balance.
-- ════════════════════════════════════════════════════════════════════

-- Euro balance, stored with 2-decimal precision.
alter table public.profiles
  add column if not exists wallet_balance numeric(12,2) not null default 0;

-- Optional: a ledger of credit→wallet conversions and wallet spends, for
-- history/audit. The app works without it (it updates profiles.wallet_balance
-- directly), but this gives you a paper trail.
create table if not exists public.wallet_ledger (
  id          bigint generated by default as identity primary key,
  user_id     uuid references public.profiles(id) on delete cascade,
  kind        text not null,              -- 'convert_in' | 'spend' | 'admin_adjust'
  credits     integer,                    -- credits consumed (for conversions)
  euros       numeric(12,2) not null,     -- +adds / -spends to the wallet
  ref         text,                        -- voucher code / note
  created_at  timestamptz not null default now()
);

create index if not exists wallet_ledger_user_idx on public.wallet_ledger (user_id, created_at desc);

alter table public.wallet_ledger enable row level security;

-- Users may read and append their own ledger rows.
drop policy if exists "wallet_ledger own read" on public.wallet_ledger;
create policy "wallet_ledger own read"
  on public.wallet_ledger for select to authenticated
  using (auth.uid() = user_id);

drop policy if exists "wallet_ledger own insert" on public.wallet_ledger;
create policy "wallet_ledger own insert"
  on public.wallet_ledger for insert to authenticated
  with check (auth.uid() = user_id);
